analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

  errors:
      constant_identifier_names: ignore
      invalid_annotation_target: ignore
  include: package:flutter_lints/flutter.yaml

