name: quizz_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  flutter_math_fork:
    git:
      url: https://github.com/simpleclub/flutter_math.git
      ref: "6e84b607c5c0e00dd1f3d4bd30ef3f1628053328"

  cupertino_icons: ^1.0.8
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  flutter_bloc: ^9.1.1
  path_provider: ^2.1.5
  equatable: ^2.0.7
  injectable: ^2.5.1
  injectable_generator: ^2.6.2
  get_it: ^8.2.0
  freezed_annotation: ^2.3.0
  json_annotation: ^4.9.0
  flutter_svg: ^2.2.0
  smooth_page_indicator: ^1.2.1
  go_router: ^16.1.0
  flutter_tex: ^5.1.10
  collection: ^1.19.0
  intl: ^0.20.2
  font_awesome_flutter: ^10.9.1
  share_plus: ^11.1.0
  hive_test: ^1.0.1
  mocktail: ^1.0.4
  bloc_test: ^10.0.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  hive_generator: ^2.0.1
  flutter_gen_runner: ^5.10.0
  freezed: ^2.3.0
  json_serializable: ^6.7.0

flutter_gen:
  output: lib/resource/ # Optional (default: lib/gen/)
  line_length: 80


  assets:
    enabled: true

    outputs:
      class_name: QuizzAsset
      package_parameter_enabled: false

flutter:
  generate: true
  uses-material-design: true



  assets:
    - assets/json/questions.json
    - assets/icons/
    - assets/icons/avatar/
    - assets/icons/home/
    - assets/icons/splash/
    - assets/icons/leader_board/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
